# Generated by Django 3.2.19 on 2023-07-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20230701_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
