# Generated by Django 3.2.19 on 2023-07-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_published_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreview',
            name='slug',
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='description',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
