# Generated by Django 3.2.19 on 2023-07-03 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20230702_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='has_formats',
            new_name='has_options',
        ),
    ]
