# Generated by Django 3.2.19 on 2023-07-18 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20230717_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='published_on',
        ),
    ]
